// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYaYYiy0dUU8hiXfFSraciUpbMdeK3aWI',
    appId: '1:568687133719:web:0a2f99462abc18a839c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    authDomain: 'e-comm-firebase-9c2e8.firebaseapp.com',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    measurementId: 'G-JX6L3FCTYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNQ2SglIlrKCcOS-D1Q_NuJcVs0YvWfA',
    appId: '1:568687133719:android:39ab7b9c220237e939c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfHm6RgrVfTYT_o6tT9f4Ah8Yp7LCWVI',
    appId: '1:568687133719:ios:499b9beaf38431ad39c852',
    messagingSenderId: '568687133719',
    projectId: 'e-comm-firebase-9c2e8',
    storageBucket: 'e-comm-firebase-9c2e8.appspot.com',
    androidClientId: '568687133719-39f2gbprotsptgbfoio00af1tgav2bgk.apps.googleusercontent.com',
    iosClientId: '568687133719-uov7j564hbhkfid6gefp2nulm18fers9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
